# Generated by Django 3.2.9 on 2021-12-04 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
