# Generated by Django 3.2.9 on 2021-12-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20211203_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(help_text=' ex. name@gmail.com', max_length=50)),
                ('image', models.ImageField(default='users_images/user_icon.png', upload_to='users_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(default='managers_images/manager_icon.png', upload_to='managers_images/'),
        ),
    ]
