# Generated by Django 3.2.9 on 2021-12-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_clientsemails_clientsinfo_clientsphones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsinfo',
            name='phoneNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.clientsphones'),
        ),
    ]
