# Generated by Django 3.2.9 on 2021-12-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_clientsinfo_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsemails',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='clientsemails',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='clientsemails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientsinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientsinfo',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='clientsinfo',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='clientsinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientsinfo',
            name='head',
        ),
        migrations.RemoveField(
            model_name='clientsinfo',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='clientsinfo',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='clientsinfo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='clientsphones',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='clientsphones',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='clientsphones',
            name='phoneNumber',
        ),
    ]
