# Generated by Django 3.2.9 on 2021-12-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_auto_20211204_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientsEmails',
        ),
        migrations.DeleteModel(
            name='ClientsInfo',
        ),
        migrations.DeleteModel(
            name='ClientsPhones',
        ),
    ]
