# Generated by Django 3.2.9 on 2021-12-11 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsphones',
            name='phoneNumber',
            field=models.CharField(help_text='e.g. +380991234567', max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,12}$')]),
        ),
    ]
