# Generated by Django 3.2.9 on 2021-12-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_auto_20211212_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectslist',
            old_name='name',
            new_name='p_name',
        ),
    ]
