# Generated by Django 3.2.9 on 2021-12-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_interplays_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interplays',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
