# Generated by Django 3.2.9 on 2021-12-13 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_app', '0007_alter_interplays_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterPlays',
            new_name='InterPlaysList',
        ),
    ]
