# Generated by Django 3.2.9 on 2021-12-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_alter_interplayslist_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interplayslist',
            name='client',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
