# Generated by Django 3.2.9 on 2021-12-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_alter_interplayslist_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interplayslist',
            name='client',
        ),
    ]
