# Generated by Django 3.2.9 on 2021-12-18 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_alter_interplayslist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interplayslist',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(-5), django.core.validators.MinValueValidator(5)]),
        ),
    ]
