# Generated by Django 3.2.9 on 2021-12-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_alter_interplayslist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interplayslist',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
