# Generated by Django 3.2.9 on 2021-12-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_alter_interplayslist_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsemails',
            options={'ordering': ['-date_created'], 'verbose_name': 'ClientsEmails', 'verbose_name_plural': 'ClientsEmails'},
        ),
        migrations.AlterModelOptions(
            name='clientsinfo',
            options={'ordering': ['-date_created'], 'permissions': (('clients_info_edit', 'Edit Client Information'),), 'verbose_name': 'ClientsInfo', 'verbose_name_plural': 'ClientsInfo'},
        ),
        migrations.AlterModelOptions(
            name='clientsphones',
            options={'ordering': ['-date_created'], 'verbose_name': 'ClientsPhones', 'verbose_name_plural': 'ClientsPhones'},
        ),
        migrations.AlterModelOptions(
            name='interplayslist',
            options={'ordering': ['-date_created'], 'verbose_name': 'InterPlaysList', 'verbose_name_plural': 'InterPlaysList'},
        ),
        migrations.AlterModelOptions(
            name='projectslist',
            options={'ordering': ['-date_created'], 'verbose_name': 'ProjectsList', 'verbose_name_plural': 'ProjectsList'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['-date_created'], 'verbose_name': 'Tags', 'verbose_name_plural': 'Tags'},
        ),
    ]
