# Generated by Django 3.2.9 on 2021-12-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_auto_20211219_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsinfo',
            options={'ordering': ['-date_created'], 'verbose_name': 'ClientsInfo', 'verbose_name_plural': 'ClientsInfo'},
        ),
    ]
