# Generated by Django 3.2.9 on 2021-12-24 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0021_tags_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsinfo',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
