# Generated by Django 3.2.9 on 2021-12-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_alter_clientsinfo_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interplayslist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectslist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
