# Generated by Django 3.2.9 on 2021-12-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_auto_20211225_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsemails',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm_app.clientsinfo'),
        ),
    ]
