# Generated by Django 3.2.9 on 2021-12-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_alter_clientsemails_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsinfo',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientsinfo',
            name='phone',
            field=models.TextField(blank=True),
        ),
    ]
