# Generated by Django 3.2.9 on 2022-01-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0027_auto_20211226_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientsinfo',
            name='phone',
        ),
    ]
